apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: cost-analysis
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ${IMAGE_REPOSITORY}/cost-analysis
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: cost-analysis
      chartPath: deploy/helm
      valuesFiles:
      - ${VALUES_LOCATION}/cost-analysis.yaml